# Generated by Django 2.0.2 on 2018-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images')),
                ('body_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
